version: '3'

services:
  db:
    image: postgres:15.3
    restart: always
    ports: 
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: magic-platform-db
    volumes:
      - ./postgres:/var/lib/postgresql/data
